- name: "Setup Pi"
  hosts: localhost
  become: yes
  connection: local
  vars:
    username: "{{ lookup('env', 'USER') }}"
#  vars_prompt:
#    - name: password
#      prompt: "What is the new password (Enter to skip)?"
#      private: yes
  roles:
    - install-pihole
#    - common
#    - setup-ssh
#    - install-java
#    - install-awscli
#    - install-dynamodb
#    - install-mosquitto
