---
- name: Check if Mosquitto is installed
  package:
    name: mosquitto
    state: present
  check_mode: true
  register: mosquitto_installed

- name: Install Mosquitto
  shell: apt install -y mosquitto mosquitto-clients
  when: mosquitto_installed is failed

- name: Enable Mosquitto listener port
  lineinfile:
    path: "{{ mosquitto_config_file }}"
    state: present
    regexp: "listener 1883"
    line: "listener 1883"

- name: Enable Mosquitto anonymous clients
  lineinfile:
    path: "{{ mosquitto_config_file }}"
    state: present
    regexp: "allow_anonymous true"
    line: "allow_anonymous true"

- name: Setup Mosquitto to run automatically at start time
  shell: systemctl enable mosquitto.service
  when: mosquitto_installed is failed
