---
- name: Make DynamoDB directory
  file:
    path: "{{ dynamodb_dir }}"
    state: directory
    mode: '0755'

- name: Get DynamoDB binary
  get_url:
    url: "https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/dynamodb_local_latest.tar.gz"
    dest: "{{ dynamodb_dir }}/dynamodb_local.tar.gz"

- name: Extract DynamoDB binary
  unarchive:
    src: "{{ dynamodb_dir }}/dynamodb_local.tar.gz"
    dest: "{{ dynamodb_dir }}"
  register: dynamo_path

- name: Start DynamoDB
  shell: "java -Djava.library.path={{ dynamodb_dir }}/DynamoDBLocal_Lib/ -jar {{ dynamodb_dir }}/DynamoDBLocal.jar -sharedDb"
