---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400       # Run if older than 24 hours

- name: Setup aliases file
  template:
    src: .bash_profile.j2
    dest: /home/{{ USERNAME }}/.bash_profile
    mode: 0755


